# Generated by Django 2.2 on 2022-05-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
