# Generated by Django 2.2 on 2022-05-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0003_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
